@startuml
actor cliente

boundary "Tela de compra" as Tela
control "PedidoController" as Controller
control "PedidoService" as Service
entity "Pedido" as Pedido
entity "Estoque" as Estoque

Cliente -> Tela : selecionarProduto(produto, quantidade)
Tela -> Controller : realizarCompras(produto, quantidade)
Controller -> Service : verificarEstoque(produto, quantidade)
Service -> Estoque : consultarQuantidade(produto)

Estoque --> Service : quantidadeDisponivel

alt Estoque Disponivel
    Controller -> Service : criarPedido(produto, quantidade)
    Service -> estoque : atualizarQuantidade(produto, quantidade)
    Service --> Controller : compraConfirmada
    Controller -> Tela : exibirConfirmacaoPedido()
    Tela -> Cliente : compraRealizada()
else Estoque Insuficiente
    Service --> Controller : estoqueInsuficiente
    Controller -> Tela : exibirMensagemErro()
    Tela -> Cliente : informarEstoqueInsuficiente()
end




@enduml 