@startuml
actor Usuario
participant Sistema
participant BD

Usuario -> Sistema : informarCredenciais()
Sistema -> BD : validarUsuario()
BD --> Sistema : ok
Sistema --> Usuario : acessoLiberado()
@enduml