class Aluno {
    iDaluno
    cadastrarAluno()
}

class Plano {
}

class Pagamento {

}

class Acesso {

}

class Aula {

}

class Agendamento {

}

class Presenca {

}

class AvaliacaoFisica {

}

class Notificacao {

}

abstract class Funcionario {

}

class Instrutor {

}

class Recepcionista {
}

class Gerente {
}